//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.30 at 05:16:20 PM PST 
//


package pipeline.jaxb;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for conditionalModule complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="conditionalModule">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="sourceCode" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *         &lt;element name="authors" type="{}authors" maxOccurs="unbounded"/>
 *         &lt;element name="citations" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *         &lt;element name="executableAuthors" type="{}authors" maxOccurs="unbounded"/>
 *         &lt;element name="executableProvenance" type="{}executableProvenance"/>
 *         &lt;element name="input" type="{}parameter" maxOccurs="unbounded"/>
 *         &lt;element name="metadata" type="{}metadata"/>
 *         &lt;element name="output" type="{}parameter" maxOccurs="unbounded"/>
 *         &lt;element name="tag" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="uri" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/choice>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="package" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="executableVersion" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="description" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="location" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="posX" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="posY" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="rotation" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="icon" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="advancedOptions" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="hasMetadata" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "conditionalModule", propOrder = {
    "sourceCode",
    "authors",
    "citations",
    "executableAuthors",
    "executableProvenance",
    "input",
    "metadata",
    "output",
    "tag",
    "uri"
})
public class ConditionalModule {

    protected List<String> sourceCode;
    protected List<Authors> authors;
    protected List<String> citations;
    protected List<Authors> executableAuthors;
    protected ExecutableProvenance executableProvenance;
    protected List<Parameter> input;
    protected Metadata metadata;
    protected List<Parameter> output;
    protected String tag;
    protected String uri;
    @XmlAttribute(name = "id", required = true)
    protected String id;
    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "package")
    protected String _package;
    @XmlAttribute(name = "version")
    protected String version;
    @XmlAttribute(name = "executableVersion")
    protected String executableVersion;
    @XmlAttribute(name = "description")
    protected String description;
    @XmlAttribute(name = "location", required = true)
    protected String location;
    @XmlAttribute(name = "posX", required = true)
    protected BigInteger posX;
    @XmlAttribute(name = "posY", required = true)
    protected BigInteger posY;
    @XmlAttribute(name = "rotation")
    protected BigInteger rotation;
    @XmlAttribute(name = "icon")
    protected String icon;
    @XmlAttribute(name = "advancedOptions")
    protected String advancedOptions;
    @XmlAttribute(name = "hasMetadata")
    protected Boolean hasMetadata;

    public ConditionalModule() {
    }

    
    public ConditionalModule(pipeline.client.Module module, int i)
    {
        //Basic
        this.posX = BigInteger.valueOf(module.getX());
        this.posY = BigInteger.valueOf(module.getY());
        this.rotation = BigInteger.valueOf(module.getRotate());
        this.id = module.getName() + "_" + i;
        this.name = module.getName();
        this.description = module.getDescriptions();
        
        
        this.authors = new ArrayList<Authors>();
        Authors authList = new Authors();
        for (pipeline.client.Author auth : module.getAuthors())
        {
            authList.author.add(new Author(auth));
        }
        this.authors.add(authList);
        
        this.executableAuthors = new ArrayList<Authors>();
        authList = new Authors();
        for (pipeline.client.Author auth : module.getAuthors())
        {
            authList.author.add(new Author(auth));
        }
        this.executableAuthors.add(authList);
        
        
        this.input = new ArrayList<Parameter>();
        for (pipeline.client.Input in : module.getInputs())
        {
            this.input.add(new Parameter(in));
        }
        
        this.output = new ArrayList<Parameter>();
        for(pipeline.client.Output out : module.getOutputsTrue())
        {
            this.output.add(new Parameter(out));
        }
        for(pipeline.client.Output out : module.getOutputsFalse())
        {
            this.output.add(new Parameter(out));
        }
    }
    
    /**
     * Gets the value of the sourceCode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sourceCode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSourceCode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getSourceCode() {
        if (sourceCode == null) {
            sourceCode = new ArrayList<String>();
        }
        return this.sourceCode;
    }

    /**
     * Gets the value of the authors property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the authors property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAuthors().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Authors }
     * 
     * 
     */
    public List<Authors> getAuthors() {
        if (authors == null) {
            authors = new ArrayList<Authors>();
        }
        return this.authors;
    }

    /**
     * Gets the value of the citations property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the citations property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCitations().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getCitations() {
        if (citations == null) {
            citations = new ArrayList<String>();
        }
        return this.citations;
    }

    /**
     * Gets the value of the executableAuthors property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the executableAuthors property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExecutableAuthors().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Authors }
     * 
     * 
     */
    public List<Authors> getExecutableAuthors() {
        if (executableAuthors == null) {
            executableAuthors = new ArrayList<Authors>();
        }
        return this.executableAuthors;
    }

    /**
     * Gets the value of the executableProvenance property.
     * 
     * @return
     *     possible object is
     *     {@link ExecutableProvenance }
     *     
     */
    public ExecutableProvenance getExecutableProvenance() {
        return executableProvenance;
    }

    /**
     * Sets the value of the executableProvenance property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExecutableProvenance }
     *     
     */
    public void setExecutableProvenance(ExecutableProvenance value) {
        this.executableProvenance = value;
    }

    /**
     * Gets the value of the input property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the input property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInput().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Parameter }
     * 
     * 
     */
    public List<Parameter> getInput() {
        if (input == null) {
            input = new ArrayList<Parameter>();
        }
        return this.input;
    }

    /**
     * Gets the value of the metadata property.
     * 
     * @return
     *     possible object is
     *     {@link Metadata }
     *     
     */
    public Metadata getMetadata() {
        return metadata;
    }

    /**
     * Sets the value of the metadata property.
     * 
     * @param value
     *     allowed object is
     *     {@link Metadata }
     *     
     */
    public void setMetadata(Metadata value) {
        this.metadata = value;
    }

    /**
     * Gets the value of the output property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the output property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOutput().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Parameter }
     * 
     * 
     */
    public List<Parameter> getOutput() {
        if (output == null) {
            output = new ArrayList<Parameter>();
        }
        return this.output;
    }

    /**
     * Gets the value of the tag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTag() {
        return tag;
    }

    /**
     * Sets the value of the tag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTag(String value) {
        this.tag = value;
    }

    /**
     * Gets the value of the uri property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUri() {
        return uri;
    }

    /**
     * Sets the value of the uri property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUri(String value) {
        this.uri = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the package property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPackage() {
        return _package;
    }

    /**
     * Sets the value of the package property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPackage(String value) {
        this._package = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the executableVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExecutableVersion() {
        return executableVersion;
    }

    /**
     * Sets the value of the executableVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExecutableVersion(String value) {
        this.executableVersion = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the location property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocation() {
        return location;
    }

    /**
     * Sets the value of the location property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocation(String value) {
        this.location = value;
    }

    /**
     * Gets the value of the posX property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPosX() {
        return posX;
    }

    /**
     * Sets the value of the posX property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPosX(BigInteger value) {
        this.posX = value;
    }

    /**
     * Gets the value of the posY property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPosY() {
        return posY;
    }

    /**
     * Sets the value of the posY property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPosY(BigInteger value) {
        this.posY = value;
    }

    /**
     * Gets the value of the rotation property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRotation() {
        return rotation;
    }

    /**
     * Sets the value of the rotation property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRotation(BigInteger value) {
        this.rotation = value;
    }

    /**
     * Gets the value of the icon property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIcon() {
        return icon;
    }

    /**
     * Sets the value of the icon property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIcon(String value) {
        this.icon = value;
    }

    /**
     * Gets the value of the advancedOptions property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdvancedOptions() {
        return advancedOptions;
    }

    /**
     * Sets the value of the advancedOptions property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdvancedOptions(String value) {
        this.advancedOptions = value;
    }

    /**
     * Gets the value of the hasMetadata property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isHasMetadata() {
        return hasMetadata;
    }

    /**
     * Sets the value of the hasMetadata property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setHasMetadata(Boolean value) {
        this.hasMetadata = value;
    }

}
