//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.30 at 05:16:20 PM PST 
//


package pipeline.jaxb;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for format complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="format">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="cardinality" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="cardinalityBase" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="transformationBase" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "format")
public class Format {

    @XmlAttribute(name = "type")
    protected String type;
    @XmlAttribute(name = "cardinality")
    protected BigInteger cardinality;
    @XmlAttribute(name = "cardinalityBase")
    protected String cardinalityBase;
    @XmlAttribute(name = "transformationBase")
    protected String transformationBase;

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the cardinality property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCardinality() {
        return cardinality;
    }

    /**
     * Sets the value of the cardinality property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCardinality(BigInteger value) {
        this.cardinality = value;
    }

    /**
     * Gets the value of the cardinalityBase property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardinalityBase() {
        return cardinalityBase;
    }

    /**
     * Sets the value of the cardinalityBase property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardinalityBase(String value) {
        this.cardinalityBase = value;
    }

    /**
     * Gets the value of the transformationBase property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransformationBase() {
        return transformationBase;
    }

    /**
     * Sets the value of the transformationBase property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransformationBase(String value) {
        this.transformationBase = value;
    }

}
