//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.17 at 10:32:06 AM PST 
//


package pipeline.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for metadataValue complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="metadataValue">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="stringExtract" type="{}stringExtract"/>
 *       &lt;/choice>
 *       &lt;attribute name="valueOption" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="valueValue" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "metadataValue", propOrder = {
    "stringExtract"
})
public class MetadataValue {

    protected StringExtract stringExtract;
    @XmlAttribute(name = "valueOption")
    protected String valueOption;
    @XmlAttribute(name = "valueValue")
    protected String valueValue;

    /**
     * Gets the value of the stringExtract property.
     * 
     * @return
     *     possible object is
     *     {@link StringExtract }
     *     
     */
    public StringExtract getStringExtract() {
        return stringExtract;
    }

    /**
     * Sets the value of the stringExtract property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringExtract }
     *     
     */
    public void setStringExtract(StringExtract value) {
        this.stringExtract = value;
    }

    /**
     * Gets the value of the valueOption property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValueOption() {
        return valueOption;
    }

    /**
     * Sets the value of the valueOption property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValueOption(String value) {
        this.valueOption = value;
    }

    /**
     * Gets the value of the valueValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValueValue() {
        return valueValue;
    }

    /**
     * Sets the value of the valueValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValueValue(String value) {
        this.valueValue = value;
    }

}
