//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.17 at 10:32:06 AM PST 
//


package pipeline.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for metadataName complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="metadataName">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="stringExtract" type="{}stringExtract"/>
 *       &lt;/choice>
 *       &lt;attribute name="nameOption" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="nameValue" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "metadataName", propOrder = {
    "stringExtract"
})
public class MetadataName {

    protected StringExtract stringExtract;
    @XmlAttribute(name = "nameOption")
    protected String nameOption;
    @XmlAttribute(name = "nameValue")
    protected String nameValue;

    /**
     * Gets the value of the stringExtract property.
     * 
     * @return
     *     possible object is
     *     {@link StringExtract }
     *     
     */
    public StringExtract getStringExtract() {
        return stringExtract;
    }

    /**
     * Sets the value of the stringExtract property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringExtract }
     *     
     */
    public void setStringExtract(StringExtract value) {
        this.stringExtract = value;
    }

    /**
     * Gets the value of the nameOption property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameOption() {
        return nameOption;
    }

    /**
     * Sets the value of the nameOption property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameOption(String value) {
        this.nameOption = value;
    }

    /**
     * Gets the value of the nameValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameValue() {
        return nameValue;
    }

    /**
     * Sets the value of the nameValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameValue(String value) {
        this.nameValue = value;
    }

}
