//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.30 at 05:16:20 PM PST 
//


package pipeline.jaxb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the pipeline.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: pipeline.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link WsOutputPreference }
     * 
     */
    public WsOutputPreference createWsOutputPreference() {
        return new WsOutputPreference();
    }

    /**
     * Create an instance of {@link Binary }
     * 
     */
    public Binary createBinary() {
        return new Binary();
    }

    /**
     * Create an instance of {@link Citations }
     * 
     */
    public Citations createCitations() {
        return new Citations();
    }

    /**
     * Create an instance of {@link Studygroup }
     * 
     */
    public Studygroup createStudygroup() {
        return new Studygroup();
    }

    /**
     * Create an instance of {@link ViewerModule }
     * 
     */
    public ViewerModule createViewerModule() {
        return new ViewerModule();
    }

    /**
     * Create an instance of {@link Data }
     * 
     */
    public Data createData() {
        return new Data();
    }

    /**
     * Create an instance of {@link Architecture }
     * 
     */
    public Architecture createArchitecture() {
        return new Architecture();
    }

    /**
     * Create an instance of {@link Annotation }
     * 
     */
    public Annotation createAnnotation() {
        return new Annotation();
    }

    /**
     * Create an instance of {@link Transform }
     * 
     */
    public Transform createTransform() {
        return new Transform();
    }

    /**
     * Create an instance of {@link DirSourceFilter }
     * 
     */
    public DirSourceFilter createDirSourceFilter() {
        return new DirSourceFilter();
    }

    /**
     * Create an instance of {@link Authors }
     * 
     */
    public Authors createAuthors() {
        return new Authors();
    }

    /**
     * Create an instance of {@link Author }
     * 
     */
    public Author createAuthor() {
        return new Author();
    }

    /**
     * Create an instance of {@link Values }
     * 
     */
    public Values createValues() {
        return new Values();
    }

    /**
     * Create an instance of {@link Parameter }
     * 
     */
    public Parameter createParameter() {
        return new Parameter();
    }

    /**
     * Create an instance of {@link MetadataElement }
     * 
     */
    public MetadataElement createMetadataElement() {
        return new MetadataElement();
    }

    /**
     * Create an instance of {@link Style }
     * 
     */
    public Style createStyle() {
        return new Style();
    }

    /**
     * Create an instance of {@link StudyGroups }
     * 
     */
    public StudyGroups createStudyGroups() {
        return new StudyGroups();
    }

    /**
     * Create an instance of {@link Dependencies }
     * 
     */
    public Dependencies createDependencies() {
        return new Dependencies();
    }

    /**
     * Create an instance of {@link ModuleGroup }
     * 
     */
    public ModuleGroup createModuleGroup() {
        return new ModuleGroup();
    }

    /**
     * Create an instance of {@link Value }
     * 
     */
    public Value createValue() {
        return new Value();
    }

    /**
     * Create an instance of {@link MetadataValue }
     * 
     */
    public MetadataValue createMetadataValue() {
        return new MetadataValue();
    }

    /**
     * Create an instance of {@link Connections }
     * 
     */
    public Connections createConnections() {
        return new Connections();
    }

    /**
     * Create an instance of {@link Metadata }
     * 
     */
    public Metadata createMetadata() {
        return new Metadata();
    }

    /**
     * Create an instance of {@link WebServiceModule }
     * 
     */
    public WebServiceModule createWebServiceModule() {
        return new WebServiceModule();
    }

    /**
     * Create an instance of {@link DataModule }
     * 
     */
    public DataModule createDataModule() {
        return new DataModule();
    }

    /**
     * Create an instance of {@link ConditionalModule }
     * 
     */
    public ConditionalModule createConditionalModule() {
        return new ConditionalModule();
    }

    /**
     * Create an instance of {@link Module }
     * 
     */
    public Module createModule() {
        return new Module();
    }

    /**
     * Create an instance of {@link Connection }
     * 
     */
    public Connection createConnection() {
        return new Connection();
    }

    /**
     * Create an instance of {@link FileType }
     * 
     */
    public FileType createFileType() {
        return new FileType();
    }

    /**
     * Create an instance of {@link OS }
     * 
     */
    public OS createOS() {
        return new OS();
    }

    /**
     * Create an instance of {@link Styles }
     * 
     */
    public Styles createStyles() {
        return new Styles();
    }

    /**
     * Create an instance of {@link MetadataActions }
     * 
     */
    public MetadataActions createMetadataActions() {
        return new MetadataActions();
    }

    /**
     * Create an instance of {@link SystemConfig }
     * 
     */
    public SystemConfig createSystemConfig() {
        return new SystemConfig();
    }

    /**
     * Create an instance of {@link Format }
     * 
     */
    public Format createFormat() {
        return new Format();
    }

    /**
     * Create an instance of {@link StringExtract }
     * 
     */
    public StringExtract createStringExtract() {
        return new StringExtract();
    }

    /**
     * Create an instance of {@link ExecutableProvenance }
     * 
     */
    public ExecutableProvenance createExecutableProvenance() {
        return new ExecutableProvenance();
    }

    /**
     * Create an instance of {@link Variables }
     * 
     */
    public Variables createVariables() {
        return new Variables();
    }

    /**
     * Create an instance of {@link MetadataName }
     * 
     */
    public MetadataName createMetadataName() {
        return new MetadataName();
    }

    /**
     * Create an instance of {@link MetadataAction }
     * 
     */
    public MetadataAction createMetadataAction() {
        return new MetadataAction();
    }

    /**
     * Create an instance of {@link FileTypes }
     * 
     */
    public FileTypes createFileTypes() {
        return new FileTypes();
    }

    /**
     * Create an instance of {@link Pipeline }
     * 
     */
    public Pipeline createPipeline() {
        return new Pipeline();
    }

    /**
     * Create an instance of {@link Library }
     * 
     */
    public Library createLibrary() {
        return new Library();
    }

    /**
     * Create an instance of {@link Compiler }
     * 
     */
    public Compiler createCompiler() {
        return new Compiler();
    }

    /**
     * Create an instance of {@link Annotations }
     * 
     */
    public Annotations createAnnotations() {
        return new Annotations();
    }

    /**
     * Create an instance of {@link WsOutputPreferences }
     * 
     */
    public WsOutputPreferences createWsOutputPreferences() {
        return new WsOutputPreferences();
    }

    /**
     * Create an instance of {@link StudyModule }
     * 
     */
    public StudyModule createStudyModule() {
        return new StudyModule();
    }

    /**
     * Create an instance of {@link Variable }
     * 
     */
    public Variable createVariable() {
        return new Variable();
    }

}
