//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.17 at 10:32:06 AM PST 
//


package pipeline.jaxb;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for parameter complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="parameter">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="format" type="{}format"/>
 *         &lt;element name="fileTypes" type="{}fileTypes" maxOccurs="unbounded"/>
 *         &lt;element name="transform" type="{}transform" maxOccurs="unbounded"/>
 *         &lt;element name="metadataElement" type="{}metadataElement" maxOccurs="unbounded"/>
 *         &lt;element name="dependencies" type="{}dependencies"/>
 *         &lt;element name="values" type="{}values"/>
 *         &lt;element name="stringExtract" type="{}stringExtract"/>
 *       &lt;/choice>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="description" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="enabled" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="predefined" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="isMetadata" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="isListFile" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="isHideData" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="includeTransformedParameter" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="order" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="prefix" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="prefixSpaced" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="prefixAllArgs" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "parameter", propOrder = {
    "format",
    "fileTypes",
    "transform",
    "metadataElement",
    "dependencies",
    "values",
    "stringExtract"
})
public class Parameter {

    protected Format format;
    protected List<FileTypes> fileTypes;
    protected List<Transform> transform;
    protected List<MetadataElement> metadataElement;
    protected Dependencies dependencies;
    protected Values values;
    protected StringExtract stringExtract;
    @XmlAttribute(name = "id")
    protected String id;
    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "description")
    protected String description;
    @XmlAttribute(name = "enabled")
    protected Boolean enabled;
    @XmlAttribute(name = "required")
    protected Boolean required;
    @XmlAttribute(name = "predefined")
    protected Boolean predefined;
    @XmlAttribute(name = "isMetadata")
    protected Boolean isMetadata;
    @XmlAttribute(name = "isListFile")
    protected Boolean isListFile;
    @XmlAttribute(name = "isHideData")
    protected Boolean isHideData;
    @XmlAttribute(name = "includeTransformedParameter")
    protected Boolean includeTransformedParameter;
    @XmlAttribute(name = "order")
    protected BigInteger order;
    @XmlAttribute(name = "prefix")
    protected String prefix;
    @XmlAttribute(name = "prefixSpaced")
    protected Boolean prefixSpaced;
    @XmlAttribute(name = "prefixAllArgs")
    protected Boolean prefixAllArgs;

    /**
     * Gets the value of the format property.
     * 
     * @return
     *     possible object is
     *     {@link Format }
     *     
     */
    public Format getFormat() {
        return format;
    }

    /**
     * Sets the value of the format property.
     * 
     * @param value
     *     allowed object is
     *     {@link Format }
     *     
     */
    public void setFormat(Format value) {
        this.format = value;
    }

    /**
     * Gets the value of the fileTypes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fileTypes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFileTypes().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FileTypes }
     * 
     * 
     */
    public List<FileTypes> getFileTypes() {
        if (fileTypes == null) {
            fileTypes = new ArrayList<FileTypes>();
        }
        return this.fileTypes;
    }

    /**
     * Gets the value of the transform property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the transform property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTransform().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Transform }
     * 
     * 
     */
    public List<Transform> getTransform() {
        if (transform == null) {
            transform = new ArrayList<Transform>();
        }
        return this.transform;
    }

    /**
     * Gets the value of the metadataElement property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the metadataElement property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMetadataElement().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MetadataElement }
     * 
     * 
     */
    public List<MetadataElement> getMetadataElement() {
        if (metadataElement == null) {
            metadataElement = new ArrayList<MetadataElement>();
        }
        return this.metadataElement;
    }

    /**
     * Gets the value of the dependencies property.
     * 
     * @return
     *     possible object is
     *     {@link Dependencies }
     *     
     */
    public Dependencies getDependencies() {
        return dependencies;
    }

    /**
     * Sets the value of the dependencies property.
     * 
     * @param value
     *     allowed object is
     *     {@link Dependencies }
     *     
     */
    public void setDependencies(Dependencies value) {
        this.dependencies = value;
    }

    /**
     * Gets the value of the values property.
     * 
     * @return
     *     possible object is
     *     {@link Values }
     *     
     */
    public Values getValues() {
        return values;
    }

    /**
     * Sets the value of the values property.
     * 
     * @param value
     *     allowed object is
     *     {@link Values }
     *     
     */
    public void setValues(Values value) {
        this.values = value;
    }

    /**
     * Gets the value of the stringExtract property.
     * 
     * @return
     *     possible object is
     *     {@link StringExtract }
     *     
     */
    public StringExtract getStringExtract() {
        return stringExtract;
    }

    /**
     * Sets the value of the stringExtract property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringExtract }
     *     
     */
    public void setStringExtract(StringExtract value) {
        this.stringExtract = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the enabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isEnabled() {
        return enabled;
    }

    /**
     * Sets the value of the enabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setEnabled(Boolean value) {
        this.enabled = value;
    }

    /**
     * Gets the value of the required property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isRequired() {
        return required;
    }

    /**
     * Sets the value of the required property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRequired(Boolean value) {
        this.required = value;
    }

    /**
     * Gets the value of the predefined property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPredefined() {
        return predefined;
    }

    /**
     * Sets the value of the predefined property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPredefined(Boolean value) {
        this.predefined = value;
    }

    /**
     * Gets the value of the isMetadata property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsMetadata() {
        return isMetadata;
    }

    /**
     * Sets the value of the isMetadata property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsMetadata(Boolean value) {
        this.isMetadata = value;
    }

    /**
     * Gets the value of the isListFile property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsListFile() {
        return isListFile;
    }

    /**
     * Sets the value of the isListFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsListFile(Boolean value) {
        this.isListFile = value;
    }

    /**
     * Gets the value of the isHideData property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsHideData() {
        return isHideData;
    }

    /**
     * Sets the value of the isHideData property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsHideData(Boolean value) {
        this.isHideData = value;
    }

    /**
     * Gets the value of the includeTransformedParameter property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIncludeTransformedParameter() {
        return includeTransformedParameter;
    }

    /**
     * Sets the value of the includeTransformedParameter property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIncludeTransformedParameter(Boolean value) {
        this.includeTransformedParameter = value;
    }

    /**
     * Gets the value of the order property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getOrder() {
        return order;
    }

    /**
     * Sets the value of the order property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setOrder(BigInteger value) {
        this.order = value;
    }

    /**
     * Gets the value of the prefix property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrefix() {
        return prefix;
    }

    /**
     * Sets the value of the prefix property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrefix(String value) {
        this.prefix = value;
    }

    /**
     * Gets the value of the prefixSpaced property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPrefixSpaced() {
        return prefixSpaced;
    }

    /**
     * Sets the value of the prefixSpaced property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPrefixSpaced(Boolean value) {
        this.prefixSpaced = value;
    }

    /**
     * Gets the value of the prefixAllArgs property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPrefixAllArgs() {
        return prefixAllArgs;
    }

    /**
     * Sets the value of the prefixAllArgs property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPrefixAllArgs(Boolean value) {
        this.prefixAllArgs = value;
    }

}
