//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.26 at 09:34:10 PM PST 
//


package pipeline.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for systemConfig complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="systemConfig">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="architecture" type="{}architecture"/>
 *         &lt;element name="OS" type="{}OS"/>
 *         &lt;element name="compiler" type="{}compiler"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "systemConfig", propOrder = {
    "architecture",
    "os",
    "compiler"
})
public class SystemConfig {

    protected Architecture architecture;
    @XmlElement(name = "OS")
    protected OS os;
    protected Compiler compiler;

    /**
     * Gets the value of the architecture property.
     * 
     * @return
     *     possible object is
     *     {@link Architecture }
     *     
     */
    public Architecture getArchitecture() {
        return architecture;
    }

    /**
     * Sets the value of the architecture property.
     * 
     * @param value
     *     allowed object is
     *     {@link Architecture }
     *     
     */
    public void setArchitecture(Architecture value) {
        this.architecture = value;
    }

    /**
     * Gets the value of the os property.
     * 
     * @return
     *     possible object is
     *     {@link OS }
     *     
     */
    public OS getOS() {
        return os;
    }

    /**
     * Sets the value of the os property.
     * 
     * @param value
     *     allowed object is
     *     {@link OS }
     *     
     */
    public void setOS(OS value) {
        this.os = value;
    }

    /**
     * Gets the value of the compiler property.
     * 
     * @return
     *     possible object is
     *     {@link Compiler }
     *     
     */
    public Compiler getCompiler() {
        return compiler;
    }

    /**
     * Sets the value of the compiler property.
     * 
     * @param value
     *     allowed object is
     *     {@link Compiler }
     *     
     */
    public void setCompiler(Compiler value) {
        this.compiler = value;
    }

}
