//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.17 at 10:32:06 AM PST 
//


package pipeline.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for wsOutputPreferences complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="wsOutputPreferences">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="pref" type="{}wsOutputPreference"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "wsOutputPreferences", propOrder = {
    "pref"
})
public class WsOutputPreferences {

    protected WsOutputPreference pref;

    /**
     * Gets the value of the pref property.
     * 
     * @return
     *     possible object is
     *     {@link WsOutputPreference }
     *     
     */
    public WsOutputPreference getPref() {
        return pref;
    }

    /**
     * Sets the value of the pref property.
     * 
     * @param value
     *     allowed object is
     *     {@link WsOutputPreference }
     *     
     */
    public void setPref(WsOutputPreference value) {
        this.pref = value;
    }

}
